# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/Container/PhysicalActionContainer
# Target is a subdirs project 

SUBDIRS += PhysicalActionVectorVector 
CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
