all:
	$(MAKE) -C yade-spherical-dem-simulator

clean:
	$(MAKE) -C yade-spherical-dem-simulator clean

install:
	$(MAKE) -C yade-spherical-dem-simulator install

uninstall:
	$(MAKE) -C yade-spherical-dem-simulator uninstall
