Import('*')
env.Install('$PREFIX/lib/yade$SUFFIX/pkg-fem',[
	env.SharedLibrary('FEMSetGeometry',['DataClass/GeometricalModel/FEMSetGeometry.cpp']),env.SharedLibrary('FEMNodeData',['DataClass/PhysicalParameters/FEMNodeData.cpp'],LIBS=env['LIBS']+['ParticleParameters','AABB',]),
	env.SharedLibrary('FEMSetParameters',['DataClass/PhysicalParameters/FEMSetParameters.cpp'],LIBS=env['LIBS']+['AABB',]),
	env.SharedLibrary('FEMTetrahedronData',['DataClass/PhysicalParameters/FEMTetrahedronData.cpp'],LIBS=env['LIBS']+['FEMNodeData','RigidBodyParameters','AABB']),
	env.SharedLibrary('FEMSet2Tetrahedrons',['Engine/EngineUnit/FEMSet2Tetrahedrons.cpp'],LIBS=env['LIBS']+['FEMSetParameters','FEMTetrahedronData','ParticleParameters','GeometricalModelMetaEngine','Tetrahedron']),
	env.SharedLibrary('FEMSetTextLoader',['Engine/EngineUnit/FEMSetTextLoader.cpp'],LIBS=env['LIBS']+['FEMSetParameters','FEMTetrahedronData','PhysicalParametersMetaEngine','ParticleParameters','RigidBodyParameters','Sphere','Tetrahedron'],),
	env.SharedLibrary('FEMTetrahedronStiffness',['Engine/EngineUnit/FEMTetrahedronStiffness.cpp'],LIBS=env['LIBS']+['FEMSetParameters','FEMTetrahedronData','PhysicalParametersMetaEngine','ParticleParameters']),
	env.SharedLibrary('FEMLaw',['Engine/StandAloneEngine/FEMLaw.cpp'],LIBS=env['LIBS']+['FEMTetrahedronData','ParticleParameters']),
	env.SharedLibrary('FEMBeam',['PreProcessor/FEMBeam.cpp'],LIBS=env['LIBS']+['FEMTetrahedronData','FEMSetParameters','FEMLaw','FEMSetTextLoader','FEMTetrahedronStiffness','CundallNonViscousDamping','CundallNonViscousDamping','MetaInteractingGeometry','GravityEngines','PhysicalActionContainerReseter','InteractionGeometryMetaEngine','InteractionPhysicsMetaEngine','GeometricalModelMetaEngine','PhysicalActionApplier','PhysicalParametersMetaEngine','BoundingVolumeMetaEngine','AABB','Box','RigidBodyParameters','Sphere','Tetrahedron','TranslationEngine',],),
])

