# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./RenderingEngine
# Target is a subdirs project 

SUBDIRS += GLDrawBoundingVolume \
           GLDrawGeometricalModel \
           GLDrawInteractingGeometry \
           GLDrawShadowVolume \
           OpenGLRenderingEngine 
CONFIG += release \
warn_on
TEMPLATE = subdirs
