# File generated by kdevelop qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

SUBDIRS += Container \
           DataClass \
           Engine \
           RenderingEngine \
           PreProcessor \
           PostProcessor
TEMPLATE=subdirs
CONFIG  += debug \
          thread \
warn_on

INCLUDEPATH += /usr/local/include

