# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./toolboxes/DataStructures/BodyContainer
# Target is a library:  

HEADERS += BodyVector.hpp 
SOURCES += BodyVector.cpp 
LIBS += -rdynamic
INCLUDEPATH = $(YADEINCLUDEPATH)
MOC_DIR = $(YADECOMPILATIONPATH)
UI_DIR = $(YADECOMPILATIONPATH)
OBJECTS_DIR = $(YADECOMPILATIONPATH)
DESTDIR = $(YADEDYNLIBPATH)
CONFIG += debug \
warn_on \
dll
TEMPLATE = lib
