# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./DataClass/InteractionPhysics
# Target is a subdirs project 

SUBDIRS += ElasticContactParameters \
           SDECLinkPhysics 
CONFIG += release \
warn_on
TEMPLATE = subdirs
