# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./DataClass/PhysicalParameters
# Target is a subdirs project 

SUBDIRS += FEMNodeData \
           FEMSetParameters \
           FEMTetrahedronData 
CONFIG += debug \
warn_on
TEMPLATE = subdirs
INCLUDEPATH += /usr/local/include

