# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./toolboxes/Math
# Target is a library:  

CONFIG += release \
          warn_on \
          dll 
TEMPLATE = lib 
