#! /bin/sh

# echo "With this you can have flat version of yade - all files in single directory"
# exit 0

echo 'ORGDIR=`pwd`'										> makeSymLinkFlat
echo 'ONLYNAME=`basename $1`'									>> makeSymLinkFlat
echo 'TMPNAME=./yade-flat/src/$ONLYNAME'							>> makeSymLinkFlat
echo 'echo symlinking $ORGDIR/$1 to `dirname $TMPNAME`'						>> makeSymLinkFlat
echo 'TMPDIR=`dirname $TMPNAME`'								>> makeSymLinkFlat
echo 'cd $TMPDIR'										>> makeSymLinkFlat
echo 'ln -s $ORGDIR/$1 `basename $TMPNAME`'							>> makeSymLinkFlat
echo 'cd $ORGDIR'										>> makeSymLinkFlat

chmod a+x ./makeSymLinkFlat

mv yade-sandbox ../

find ./ -name "*.h"   -exec ./makeSymLinkFlat {} \;
find ./ -name "*.c"   -exec ./makeSymLinkFlat {} \;
find ./ -name "*.hpp" -exec ./makeSymLinkFlat {} \;
find ./ -name "*.tpp" -exec ./makeSymLinkFlat {} \;
find ./ -name "*.ipp" -exec ./makeSymLinkFlat {} \;
find ./ -name "*.cpp" -exec ./makeSymLinkFlat {} \;
find ./ -name "*.ui"  -exec ./makeSymLinkFlat {} \;

mv ../yade-sandbox ./

cd yade-flat
#symlinks -rcsd ./
#symlinks -rcsd ./
cd ..

rm ./makeSymLinkFlat

