#! /bin/sh

echo 'targetdir=`dirname $1`'	> runqmake
echo 'sourcedir=`pwd`'		>> runqmake
echo 'cd targetdir'		>> runqmake
echo 'qmake'			>> runqmake
echo 'cd sourcedir'		>> runqmake

chmod 777 runqmake

find $YADEPATH -name "*.pro" -exec runqmake {} \;       

rm runqmake

cd $YADEPATH/yade/projects/kdevelop
