#! /bin/sh

find . -iname "*.pro" -print | while read name; do grep -l CONFIG $name; done	>  ./proFilesRelease
echo './empty'                                                                  >> ./proFilesRelease
echo ' '                                                                        >  ./empty

echo 'echo CHANGING $1'								>  ./changeSet
echo 'mv $1 $1.tmp'								>> ./changeSet
echo 'cat $1.tmp | sed -e "s/= debug/= release/" > $1'				>> ./changeSet
echo 'rm $1.tmp'								>> ./changeSet

chmod a+x ./changeSet

find `cat proFilesRelease` -exec ./changeSet {} \;

## now add CONFIG entry to all .pro that do not have it.

find . -iname "*.pro" -print | while read name; do grep -L CONFIG $name; done	>  ./proFilesRelease
echo './empty'                                                                  >> ./proFilesRelease

echo 'echo CHANGING $1'								>  ./changeSet
echo 'echo "CONFIG += release \\" >> $1'					>> ./changeSet
echo 'echo "          warn_on" >> $1'						>> ./changeSet
echo 'echo "" >> $1'								>> ./changeSet

chmod a+x ./changeSet

find `cat proFilesRelease` -exec ./changeSet {} \;


## should also change the output dir and temporary compilation dir

rm ./changeSet
rm ./empty
rm ./proFilesRelease

