# File generated by kdevelop qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./Container/PhysicalActionContainer
# Target is a subdirs project 

CONFIG += debug \
          thread \
          warn_on 
TEMPLATE = subdirs 
INCLUDEPATH += /usr/local/include

