# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./DataClass/InteractionGeometry
# Target is a subdirs project 

SUBDIRS += ErrorTolerantContactModel 
CONFIG += debug \
warn_on
TEMPLATE = subdirs
