#! /bin/sh

echo ' '												>  ./empty

echo '#! /bin/sh'											>  ./changeProFiles
echo 'echo CHANGING $1'											>> ./changeProFiles
echo 'RELPATH=`echo $1 |  sed -e "s/\/[^/.]*/\\\\\\\\\/\.\./g" | sed -e "s/\/\.\.\.pro/\\\\//g"`'	>>  ./changeProFiles
#echo 'echo $RELPATH'											>> ./changeProFiles
echo 'mv $1 $1.tmp'											>> ./changeProFiles
echo 'cat $1.tmp | sed -e "s/$2/$RELPATH$3/" > $1'							>> ./changeProFiles
echo 'rm $1.tmp'											>> ./changeProFiles

chmod a+x ./changeProFiles

echo "removing YADEBINPATH .... "
find ../projects/kdevelop/  -name "*.pro" -exec fgrep -l "YADEBINPATH" {} \;				> ./proFilesModified
echo './empty'												>> ./proFilesModified
find `cat proFilesModified` -exec ./changeProFiles {} '$(YADEBINPATH)' 'bin' \;

echo "removing YADECOMPILATIONPATH .... "
find ../projects/kdevelop/  -name "*.pro" -exec fgrep -l "YADECOMPILATIONPATH" {} \;			> ./proFilesModified
echo './empty'												>> ./proFilesModified
find `cat proFilesModified` -exec ./changeProFiles {} '$(YADECOMPILATIONPATH)' 'bin\/compilation' \;

echo "removing YADEDYNLIBPATH .... "
find ../projects/kdevelop/  -name "*.pro" -exec fgrep -l "YADEDYNLIBPATH" {} \;				> ./proFilesModified
echo './empty'												>> ./proFilesModified
find `cat proFilesModified` -exec ./changeProFiles {} '$(YADEDYNLIBPATH)' 'bin\/dynlib\/linux' \;

echo "removing YADEINCLUDEPATH .... "
find ../projects/kdevelop/  -name "*.pro" -exec fgrep -l "YADEINCLUDEPATH" {} \;			> ./proFilesModified
echo './empty'												>> ./proFilesModified
find `cat proFilesModified` -exec ./changeProFiles {} '$(YADEINCLUDEPATH)' 'yade\/include' \;

rm ./changeProFiles
rm ./empty
rm ./proFilesModified

