# File generated by kdevelop qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./Container
# Target is a subdirs project 

SUBDIRS += BodyContainer \
           InteractionContainer \
           PhysicalActionContainer 
CONFIG += debug \
          thread \
          warn_on 
TEMPLATE = subdirs 
INCLUDEPATH += /usr/local/include

