# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./DataClass/GeometricalModel
# Target is a subdirs project 

SUBDIRS += LatticeSetGeometry \
           LineSegment 
CONFIG += debug \
warn_on
TEMPLATE = subdirs
