# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./preprocessors/FileGenerator/FEMBeam
# Target is a library:  

LIBS += -lSerialization \
        -lAABB \
        -lBox \
        -lPolyhedron \
        -lMath \
        -lBody \
        -lInteraction \
        -lMultiMethods \
        -lRigidBodyParameters \
        -lEngine \
        -lActionParameterInitializer \
        -lActionParameterReset \
        -lGravityCondition \
        -lCundallNonViscousMomentumDamping \
        -lCundallNonViscousForceDamping \
        -lSphere \
        -lFEMSetParameters \
        -lFEMTetrahedronData \
        -lFEMNodeData \
        -lTetrahedron \
        -lFEMSetTextLoader \
        -lFEMLaw \
        -lTranslationCondition \
        -lFEMTetrahedronStiffness \
        -lMetaInteractingGeometry \
        -rdynamic 
INCLUDEPATH = $(YADEINCLUDEPATH) 
MOC_DIR = $(YADECOMPILATIONPATH) 
UI_DIR = $(YADECOMPILATIONPATH) 
OBJECTS_DIR = $(YADECOMPILATIONPATH) 
QMAKE_LIBDIR = ../../../toolboxes/Libraries/Serialization/$(YADEDYNLIBPATH) \
               ../../../plugins/Body/BoundingVolume/AABB/$(YADEDYNLIBPATH) \
               ../../../plugins/Body/GeometricalModel/Box/$(YADEDYNLIBPATH) \
               ../../../plugins/Body/GeometricalModel/Polyhedron/$(YADEDYNLIBPATH) \
               ../../../toolboxes/Libraries/Math/$(YADEDYNLIBPATH) \
               ../../../yade/Body/Body/$(YADEDYNLIBPATH) \
               ../../../yade/Interaction/Interaction/$(YADEDYNLIBPATH) \
               ../../../toolboxes/Libraries/MultiMethods/$(YADEDYNLIBPATH) \
               ../../../plugins/Body/PhysicalParameters/RigidBodyParameters/$(YADEDYNLIBPATH) \
               ../../../yade/Engine/$(YADEDYNLIBPATH) \
               ../../../plugins/Engine/ActionParameterInitializer/$(YADEDYNLIBPATH) \
               ../../../plugins/Engine/ActionParameterReset/$(YADEDYNLIBPATH) \
               ../../../plugins/Engine/DeusExMachina/GravityCondition/$(YADEDYNLIBPATH) \
               ../../../plugins/Engine/ActionParameterFunctor/CundallNonViscousMomentumDamping/$(YADEDYNLIBPATH) \
               ../../../plugins/Engine/ActionParameterFunctor/CundallNonViscousForceDamping/$(YADEDYNLIBPATH) \
               ../../../plugins/Body/GeometricalModel/Sphere/$(YADEDYNLIBPATH) \
               ../../../plugins/Body/PhysicalParameters/FEMSetParameters/$(YADEDYNLIBPATH) \
               ../../../plugins/Body/PhysicalParameters/FEMTetrahedronData/$(YADEDYNLIBPATH) \
               ../../../plugins/Body/PhysicalParameters/FEMNodeData/$(YADEDYNLIBPATH) \
               ../../../plugins/Body/GeometricalModel/Tetrahedron/$(YADEDYNLIBPATH) \
               ../../../plugins/Body/PhysicalParametersFunctor/FEMSetTextLoader/$(YADEDYNLIBPATH) \
               ../../../plugins/Engine/InteractionSolver/FEMLaw/$(YADEDYNLIBPATH) \
               ../../../plugins/Engine/DeusExMachina/TranslationCondition/$(YADEDYNLIBPATH) \
               ../../../plugins/Body/PhysicalParametersFunctor/FEMTetrahedronStiffness/$(YADEDYNLIBPATH) \
               ../../../plugins/Body/BodyPhysicalParametersFunctor/FEMSetTextLoader/$(YADEDYNLIBPATH) \
               $(YADEDYNLIBPATH) 
QMAKE_CXXFLAGS_RELEASE += -lpthread \
                          -pthread 
QMAKE_CXXFLAGS_DEBUG += -lpthread \
                        -pthread 
DESTDIR = $(YADEDYNLIBPATH) 
CONFIG += debug \
          warn_on \
          dll 
TEMPLATE = lib 
HEADERS += FEMBeam.hpp 
SOURCES += FEMBeam.cpp 
