# vim: set filetype=python :
Import('*')
linkPlugins=env['linkPlugins']


import os.path, os

env.Install('$LIBDIR/extra',[
	# env.SharedLibrary('PeriodicInsertionSortCollider',['PeriodicInsertionSortCollider.cpp'],LIBS=env['LIBS']+linkPlugins(['InsertionSortCollider','Shop'])),
])





