# vim: set filetype=python :
Import('*')

import os.path, os

env.Install('$PREFIX/lib/yade$SUFFIX/extra',[

	env.SharedLibrary('Tetra',['tetra/Tetra.cpp'],LIBS=env['LIBS']+['Tetrahedron',
         'ParticleParameters',
         'RigidBodyParameters',
			'ElasticBodyParameters',
			'BodyMacroParameters',
         'AABB']),
	
	env.SharedLibrary('TetraTestGen',['tetra/TetraTestGen.cpp'],LIBS=env['LIBS']+['Shop','Tetra']),

	env.SharedLibrary('Shop',
		['Shop.cpp'],
		LIBS=env['LIBS']+[
			'ElasticContactLaw',
			'ElasticCohesiveLaw',
			'MacroMicroElasticRelationships',
			'ElasticCriterionTimeStepper',
			'InteractingSphere',
			'InteractingBox',
			'CundallNonViscousDamping',
			'CundallNonViscousDamping',
			'MetaInteractingGeometry',
			'GravityEngines',
			'yade-serialization',
			'yade-base',	
			'PhysicalActionContainerReseter',
			'InteractionGeometryMetaEngine',
			'InteractionPhysicsMetaEngine',
			'PhysicalActionApplier',
			'PhysicalParametersMetaEngine',
			'BoundingVolumeMetaEngine',
			'Box',
			'Sphere',
			'Tetra',
			'AABB',
			'PersistentSAPCollider',
			'ParticleParameters',
			'MetaInteractingGeometry',
			'MetaInteractingGeometry2AABB',
			'InteractingSphere2AABB',
			'InteractingBox2AABB',
			'NewtonsMomentumLaw',
			'NewtonsForceLaw',
			'LeapFrogPositionIntegrator',
			'LeapFrogOrientationIntegrator',
			'InteractingBox2InteractingSphere4SpheresContactGeometry',
			'InteractingSphere2InteractingSphere4SpheresContactGeometry',
			#'Clump',
			'yade-multimethods',
			'SpheresContactGeometry',
			'ElasticContactInteraction',
			'SimpleViscoelasticBodyParameters',
			'SDECLinkGeometry',
			'SDECLinkPhysics',
			]),
])


