# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/Engine
# Target is a subdirs project 

SUBDIRS += ActionParameterFunctor \
           ActionParameterInitializer \
           ActionParameterReset \
           DeusExMachina \
           InteractionSolver 
MOC_DIR = $(YADECOMPILATIONPATH)
UI_DIR = $(YADECOMPILATIONPATH)
OBJECTS_DIR = $(YADECOMPILATIONPATH)
CONFIG += debug \
warn_on
TEMPLATE = subdirs
