# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./yade-lib-serialization-xml
# Target is a library:  ../../../bin/yade-lib-serialization-xml

HEADERS += XMLManager.hpp \
           XMLSaxParser.hpp 
SOURCES += XMLManager.cpp \
           XMLSaxParser.cpp 
INCLUDEPATH += /usr/local/include/yade
TARGET = ../../../bin/yade-lib-serialization-xml
CONFIG += release \
warn_on \
dll
TEMPLATE = lib
