Import('*')
env.SharedLibrary('Clump',
	['Clump.cpp'],
	LIBS=env['LIBS']+[
		#'PhysicalParametersEngineUnit',
		#'Body',
		'yade-lib-multimethods',
		'yade-lib-factory',
		'yade-lib-serialization',
		'yade-lib-base',
		'Wm3Foundation'],
	CPPPATH=env['CPPPATH']+['$PREFIX/include'])
#env.Program('tryI',['tryI.cpp'],LIBS=env['LIBS']+['yade-lib-base','Wm3Foundation'])

