# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/Engine/MetaEngine/InteractionMetaEngine
# Target is a subdirs project 

SUBDIRS += BroadInteractionMetaEngine \
           InteractionPhysicsMetaEngine \
           NarrowInteractionGeometryMetaEngine 
CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
