# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/Engine/EngineUnit/PhysicalActionEngineUnit
# Target is a subdirs project 

CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
