# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/Data/Body
# Target is a subdirs project 

SUBDIRS += BoundingVolume \
           GeometricalModel \
           InteractingGeometry \
           PhysicalParameters \
           State 
MOC_DIR = $(YADECOMPILATIONPATH)
UI_DIR = $(YADECOMPILATIONPATH)
OBJECTS_DIR = $(YADECOMPILATIONPATH)
CONFIG += debug \
warn_on
TEMPLATE = subdirs
