# File generated by kdevelop qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./extensions/RenderingEngines/OpenGLRenderingEngine/GLDrawBoundingVolumeFunctor
# Target is a subdirs project 

SUBDIRS += GLDrawAABB \
           GLDrawBoundingSphere 
CONFIG += debug \
          thread \
warn_on
TEMPLATE = subdirs
INCLUDEPATH += /usr/local/include

