# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/ActionFunctor
# Target is a subdirs project 

SUBDIRS += ApplyActionForce2Particle \
	   ApplyActionMomentum2RigidBody \
	   CundallNonViscousForceDamping \
	   CundallNonViscousMomentumDamping
CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
