# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/Engine/MetaEngine/BodyMetaEngine/PhysicalParameterMetaEngine
# Target is a subdirs project 

SUBDIRS += PhysicalParametersMetaEngine 
CONFIG += release \
warn_on
TEMPLATE = subdirs
