# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./Engine
# Target is a subdirs project 

SUBDIRS += DeusExMachina \          
           MetaEngine \
           EngineUnit \
           StandAloneEngine 
CONFIG += debug \
          warn_on 
TEMPLATE = subdirs 
