# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./DataClass/GeometricalModel
# Target is a subdirs project 

SUBDIRS += Box \
           Mesh2D \
           Polyhedron \
           Sphere \
           Tetrahedron 
CONFIG += release \
warn_on
TEMPLATE = subdirs
