# File generated by kdevelop qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./DataClass/GeometricalModel
# Target is a subdirs project 

SUBDIRS += Box \
           Mesh2D \
           Polyhedron \
           Sphere \
           Tetrahedron 
CONFIG += debug \
          thread \
warn_on
TEMPLATE = subdirs
INCLUDEPATH += /usr/local/include

