# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./PreProcessor
# Target is a subdirs project 

SUBDIRS += HangingCloth 
CONFIG += release \
warn_on
TEMPLATE = subdirs
