# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/Engine/Sensor
# Target is a subdirs project 

SUBDIRS += RenderingEngine \
           DataRecorderEngine 
CONFIG += release \
warn_on
TEMPLATE = subdirs
