# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/BoundingVolumeFactory
# Target is a subdirs project 

SUBDIRS += Box2AABBFactory \
           Terrain2AABBFactory \
           Sphere2AABBFactory \
           CollisionGeometrySet2AABBFactory 
MOC_DIR = $(YADECOMPILATIONPATH)
UI_DIR = $(YADECOMPILATIONPATH)
OBJECTS_DIR = $(YADECOMPILATIONPATH)
CONFIG += debug \
warn_on
TEMPLATE = subdirs
