# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./Engine/StandAloneEngine/LatticeLaw
# Target is a library:  

INCLUDEPATH += ../../../DataClass/PhysicalParameters/LatticeNodeParameters \
               ../../../DataClass/PhysicalParameters/LatticeBeamParameters 
QMAKE_LIBDIR = /usr/local/lib/yade/yade-package-common/ \
               /usr/local/lib/yade/yade-libs/ 
DESTDIR = ../../../../../bin 
CONFIG += release \
          warn_on \
          dll 
TEMPLATE = lib 
HEADERS += LatticeLaw.hpp 
SOURCES += LatticeLaw.cpp 
