# File generated by kdevelop qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./yade-empty-lib
# Target is a library:  ../../../bin/yade-empty-lib

QMAKE_LIBDIR = /usr/local/lib/yade/yade-libs/ 
TARGET = ../../../bin/yade-empty-lib 
CONFIG += debug \
          thread \
          warn_on \
          dll 
TEMPLATE = lib 
INCLUDEPATH += /usr/local/include

