# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/CollisionFunctor
# Target is a subdirs project 

SUBDIRS += CollisionFunctor4ClosestFeatures \
           CollisionFunctor4SDECContactModel \
           CollisionFunctor4ErrorTolerant 
MOC_DIR = $(YADECOMPILATIONPATH)
UI_DIR = $(YADECOMPILATIONPATH)
OBJECTS_DIR = $(YADECOMPILATIONPATH)
CONFIG += debug \
warn_on
TEMPLATE = subdirs
