# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./Engine/EngineUnit/CundallNonViscousMomentumDamping
# Target is a library:  

LIBS += -lPhysicalActionDamper \
        -lMomentum \
        -lRigidBodyParameters \
        -rdynamic 
INCLUDEPATH += ../../../DataClass/PhysicalAction/Momentum \
               ../../../DataClass/PhysicalParameters/RigidBodyParameters \
               ../../../DataClass/PhysicalParameters/ParticleParameters \
               ../../../Engine/MetaEngine/PhysicalActionDamper 
QMAKE_LIBDIR = ../../../../../bin \
               ../../../../../bin \
               /usr/local/lib/yade/yade-libs 
QMAKE_CXXFLAGS_RELEASE += -lpthread \
                          -pthread 
QMAKE_CXXFLAGS_DEBUG += -lpthread \
                        -pthread 
DESTDIR = ../../../../../bin 
CONFIG += debug \
          warn_on \
          dll 
TEMPLATE = lib 
HEADERS += CundallNonViscousMomentumDamping.hpp 
SOURCES += CundallNonViscousMomentumDamping.cpp 
