# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./toolboxes/OpenGL
# Target is a subdirs project 

SUBDIRS += GLWindowManager 
CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
