# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./yade-lib-time
# Target is a library:  ../../../bin/yade-lib-time

TARGET = ../../../bin/yade-lib-time 
CONFIG += debug \
          warn_on \
          dll 
TEMPLATE = lib 
HEADERS += Chrono.hpp 
SOURCES += Chrono.cpp 
