# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./yade-lib-time
# Target is a library:  ../../../bin/yade-lib-time

HEADERS += Chrono.hpp 
SOURCES += Chrono.cpp 
TARGET = ../../../bin/yade-lib-time
CONFIG += release \
warn_on \
dll
TEMPLATE = lib
