# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/InteractionModel
# Target is a subdirs project 

SUBDIRS += ClosestFeatures \
           SDECContactModel 
MOC_DIR = $(YADECOMPILATIONPATH)
UI_DIR = $(YADECOMPILATIONPATH)
OBJECTS_DIR = $(YADECOMPILATIONPATH)
CONFIG += release \
warn_on
TEMPLATE = subdirs
