# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/BroadPhaseCollider
# Target is a subdirs project 

MOC_DIR = $(YADECOMPILATIONPATH) 
UI_DIR = $(YADECOMPILATIONPATH) 
OBJECTS_DIR = $(YADECOMPILATIONPATH) 
CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
SUBDIRS += SimpleBroadCollider \
           SAPCollider 
