#! /bin/sh

grep "          dll" ../projects/kdevelop/* -Rl | fgrep .svn/text-base -v 	>  ./dynamicLibs
echo './empty'									>> ./dynamicLibs

echo ' '									>  ./empty

echo 'echo NOT CHANGING $1'							>  ./changeLib
#echo 'mv $1 $1.tmp'								>> ./changeLib
#echo 'cat $1.tmp | sed -e "s/          dll/          staticlib/" > $1'		>> ./changeLib
#echo 'rm $1.tmp'								>> ./changeLib

chmod a+x ./changeLib

find `cat dynamicLibs` -exec ./changeLib {} \;

rm ./changeLib
rm ./dynamicLibs
rm ./empty
