#! /bin/sh

if [ "${YADEPATH:-nothing}" = "nothing" ];
then
  echo "ERROR:  YADEPATH is not defined, you forgot to run:";
  echo "        source ./yadeEnv YOUR_PATH_TO_YADE";
  exit 0;
else
  echo "I'm using YADEPATH="${YADEPATH};
fi

./removeSymLinks
./removeBackupFiles
./removeBinFiles
./removeCoreFiles
./removeMakefiles

rm $YADEBINPATH/.qglviewer.xml
rm $YADEPATH/yade/projects/kdevelop/yade.kdevelop.pcs
rm $YADEPATH/yade/projects/kdevelop/yade.kdevses
rm $YADEPATH/yade/projects/kdevelop/yade.tag
rm $YADEPATH/yade/projects/kdevelop/tags
rm $YADEPATH/data/log.xml
rm $YADEPATH/data/scene.xml
rm $YADEINCLUDEPATH/*


find ../ -name '$(YADEBINPATH)' -exec rm -r {} \;
find ../ -name '$(YADECOMPILATIONPATH)' -exec rm -r {} \;
find ../ -name '$(YADEDYNLIBPATH)' -exec rm -r {} \;
