#! /bin/sh

./makeSymLinks
./makeIncludes

echo 'You should run:'
echo '  >  source yadeEnv YOUR_YADE_PATH      # WARNING: _no_ trailing slash!!'
echo '  >  cd ../projects/kdevelop'
echo '  >  qmake'
echo '  >  make'
echo 'Wait till it compiles..'
echo '  >  cd $YADEBINPATH'
echo '  >  ./yade'
