#! /bin/sh

echo "finding .pro files ... "
find ../projects/kdevelop/  -name "*.pro" -exec fgrep -l "$2" {} \;		> ./proRenameClass

echo "finding .hpp files ... "
find ../src/  -name "*.hpp" -exec fgrep -l "$2" {} \;				> ./hppRenameClass

echo "finding .cpp files ... "
find ../src/  -name "*.cpp" -exec fgrep -l "$2" {} \;				> ./cppRenameClass

echo "finding .tpp files ... "
find ../src/  -name "*.tpp" -exec fgrep -l "$2" {} \;				> ./tppRenameClass

echo "finding .ipp files ... "
find ../src/  -name "*.ipp" -exec fgrep -l "$2" {} \;				> ./ippRenameClass

cat ./proRenameClass  | grep -e "\<$1\>.pro"					> ./proRenameClass2
cat ./hppRenameClass  | grep -e "\<$1\>.hpp"					> ./hppRenameClass2
cat ./cppRenameClass  | grep -e "\<$1\>.cpp"					> ./cppRenameClass2
cat ./tppRenameClass  | grep -e "\<$1\>.tpp"					> ./tppRenameClass2
cat ./ippRenameClass  | grep -e "\<$1\>.ipp"					> ./ippRenameClass2

cat ./proRenameClass2 | grep -e "\<$1\>" | sed -e "s/\<$1\>\.pro/$2.pro/"	> ./proRenameClass3
cat ./hppRenameClass2 | grep -e "\<$1\>" | sed -e "s/\<$1\>\.hpp/$2.hpp/"	> ./hppRenameClass3
cat ./cppRenameClass2 | grep -e "\<$1\>" | sed -e "s/\<$1\>\.cpp/$2.cpp/"	> ./cppRenameClass3
cat ./tppRenameClass2 | grep -e "\<$1\>" | sed -e "s/\<$1\>\.tpp/$2.tpp/"	> ./tppRenameClass3
cat ./ippRenameClass2 | grep -e "\<$1\>" | sed -e "s/\<$1\>\.ipp/$2.ipp/"	> ./ippRenameClass3



if [ -s ./proRenameClass2 ]; then
  if [ -e `cat ./proRenameClass2` ]; then
    if [ -f `cat ./proRenameClass2` ]; then
      if [ -r `cat ./proRenameClass2` ]; then
        svn mv `cat ./proRenameClass2` `cat ./proRenameClass3` $3
      fi
    fi
  fi
fi

if [ -s ./hppRenameClass2 ]; then
  if [ -e `cat ./hppRenameClass2` ]; then
    if [ -f `cat ./hppRenameClass2` ]; then
      if [ -r `cat ./hppRenameClass2` ]; then
        svn mv `cat ./hppRenameClass2` `cat ./hppRenameClass3` $3
      fi
    fi
  fi
fi

if [ -s ./cppRenameClass2 ]; then
  if [ -e `cat ./cppRenameClass2` ]; then
    if [ -f `cat ./cppRenameClass2` ]; then
      if [ -r `cat ./cppRenameClass2` ]; then
        svn mv `cat ./cppRenameClass2` `cat ./cppRenameClass3` $3
      fi
    fi
  fi
fi

if [ -s ./tppRenameClass2 ]; then
  if [ -e `cat ./tppRenameClass2` ]; then
    if [ -f `cat ./tppRenameClass2` ]; then
      if [ -r `cat ./tppRenameClass2` ]; then
        svn mv `cat ./tppRenameClass2` `cat ./tppRenameClass3` $3
      fi
    fi
  fi
fi

if [ -s ./ippRenameClass2 ]; then
  if [ -e `cat ./ippRenameClass2` ]; then
    if [ -f `cat ./ippRenameClass2` ]; then
      if [ -r `cat ./ippRenameClass2` ]; then
        svn mv `cat ./ippRenameClass2` `cat ./ippRenameClass3` $3
      fi
    fi
  fi
fi

rm ./proRenameClass*
rm ./hppRenameClass*
rm ./cppRenameClass*
rm ./tppRenameClass*
rm ./ippRenameClass*

echo "---------------------------------------------------------------------------------------"
echo "if you didn't commit in previous step, you had some svn errors, and nothing happened"
echo ""
echo "All filenames renamed, you should commit now. Next step:"
echo " - MAKE A FRESH CHECKOUT from repository, otherwise svn will fuck up process of renaming directories."
echo " - then you can do:   ./renameClassDirectories $1 $2"
echo ""

