# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./DataClass/State
# Target is a subdirs project 

CONFIG += debug \
          warn_on 
TEMPLATE = subdirs 
