#!/bin/sh
# this script must be run from yade's top-level directory!
#
# if there is file RELEASE, it will be the version number ($VERSION) and SNAPSHOT will be empty.
# Otherwise svn or bzr versioning information will be used. Errors out if RELEASE or .svn or .bzr don't exist.
#
# Takes one optional argument with the name of $DISTRIBUTION (default: unstable)
#

## DISTRIBUTION (first argument, otherwise the default "unstable")
DISTRIBUTION=$1; [ -n "$DISTRIBUTION" ] || DISTRIBUTION="unstable"

## VERSION (from RELEASE or svn or bzr)
if [ -f RELEASE ]; then	VERSION=`cat RELEASE`; SNAPSHOT=""
elif [ -d .svn ]; then VERSION="svn$( svn info | egrep '^Revision:' | cut -f2 -d' ')"; SNAPSHOT="-snapshot"
elif [ -d .bzr ]; then VERSION="bzr$( bzr revno )"; SNAPSHOT="-snapshot"
else echo 'Revision could not be determined (RELEASE or .svn or .bzr)' >2; exit 1;
fi
# compute version priority:
# * releases get 10000*version (discarding anything not digit and dot)
# * snapshots get their revision number (discarding anything not digit)
# This way, releases have always higher number than snapshots and
# both releases and snapshots are properly ordered
if [ -f RELEASE ]; then PRIORITY=$( echo 10000\*`cat RELEASE | sed s'/[^0-9.]//g'` | bc | cut -d. -f1 )
else PRIORITY=$( echo $VERSION | sed s'/[^0-9]//g' )
fi
_VERSION="-$VERSION"; echo $VERSION > VERSION
echo PRIORITY $PRIORITY
cp debian/yade.postinst-template debian/yade$_VERSION.postinst
cp debian/yade-dbg.postinst-template debian/yade$_VERSION-dbg.postinst
cp debian/yade.prerm-template debian/yade$_VERSION.prerm
cp debian/yade-dbg.prerm-template debian/yade$_VERSION-dbg.prerm
cp debian/control-template debian/control; perl -pi -e"s/\@VERSION\@/$VERSION/g; s/\@_VERSION\@/$_VERSION/g; s/\@SNAPSHOT\@/$SNAPSHOT/g; s/\@PRIORITY\@/$PRIORITY/g;" debian/control debian/yade$_VERSION.postinst debian/yade$_VERSION-dbg.postinst debian/yade$_VERSION.prerm debian/yade$_VERSION-dbg.prerm;

## debian/changelog
DEBDATE=`date -R`
cat <<EOF > debian/changelog
yade$_VERSION (1~$DISTRIBUTION) $DISTRIBUTION; urgency=low

  * Automatic debian changelog entry for yade$_VERSION

 -- Václav Šmilauer <eudoxos@arcig.cz>  $DEBDATE
EOF

