#!/bin/sh
perl -pi -e's@\baCos\b@ACos@g' $@
perl -pi -e's@\baSin\b@ASin@g' $@
perl -pi -e's@\baTan\b@ATan@g' $@
perl -pi -e's@\baTan2\b@ATan2@g' $@
perl -pi -e's@\badjoint\b@Adjoint@g' $@
perl -pi -e's@\balign\b@Align@g' $@
perl -pi -e's@\bbidiagonalize\b@Bidiagonalize@g' $@
perl -pi -e's@\bcompareArrays\b@CompareArrays@g' $@
perl -pi -e's@\bconjugate\b@Conjugate@g' $@
perl -pi -e's@\bcosinus\b@Cos@g' $@
perl -pi -e's@\bcross\b@Cross@g' $@
perl -pi -e's@\bdecomposeSwingTimesTwist\b@DecomposeSwingTimesTwist@g' $@
perl -pi -e's@\bdecomposeTwistTimesSwing\b@DecomposeTwistTimesSwing@g' $@
perl -pi -e's@\bdeterminant\b@Determinant@g' $@
perl -pi -e's@\bdiagonalTimes\b@DiagonalTimes@g' $@
perl -pi -e's@\bdot\b@Dot@g' $@
perl -pi -e's@\bdotPerp\b@DotPerp@g' $@
perl -pi -e's@\beExp\b@Exp@g' $@
perl -pi -e's@\beigenDecomposition\b@EigenDecomposition@g' $@
perl -pi -e's@\bexp\b@Exp@g' $@
perl -pi -e's@\bfAbs\b@FAbs@g' $@
perl -pi -e's@\bfMod\b@FMod@g' $@
perl -pi -e's@\bfastCos0\b@FastCos0@g' $@
perl -pi -e's@\bfastCos1\b@FastCos1@g' $@
perl -pi -e's@\bfastInvCos0\b@FastInvCos0@g' $@
perl -pi -e's@\bfastInvCos1\b@FastInvCos1@g' $@
perl -pi -e's@\bfastInvSin0\b@FastInvSin0@g' $@
perl -pi -e's@\bfastInvSin1\b@FastInvSin1@g' $@
perl -pi -e's@\bfastInvSqrt\b@FastInvSqrt@g' $@
perl -pi -e's@\bfastInvTan0\b@FastInvTan0@g' $@
perl -pi -e's@\bfastInvTan1\b@FastInvTan1@g' $@
perl -pi -e's@\bfastSin0\b@FastSin0@g' $@
perl -pi -e's@\bfastSin1\b@FastSin1@g' $@
perl -pi -e's@\bfastTan0\b@FastTan0@g' $@
perl -pi -e's@\bfastTan1\b@FastTan1@g' $@
perl -pi -e's@\bfromAngle\b@FromAngle@g' $@
perl -pi -e's@\bfromAxisAngle\b@FromAxisAngle@g' $@
perl -pi -e's@\bfromEulerAnglesXYZ\b@FromEulerAnglesXYZ@g' $@
perl -pi -e's@\bfromEulerAnglesXZY\b@FromEulerAnglesXZY@g' $@
perl -pi -e's@\bfromEulerAnglesYXZ\b@FromEulerAnglesYXZ@g' $@
perl -pi -e's@\bfromEulerAnglesYZX\b@FromEulerAnglesYZX@g' $@
perl -pi -e's@\bfromEulerAnglesZXY\b@FromEulerAnglesZXY@g' $@
perl -pi -e's@\bfromEulerAnglesZYX\b@FromEulerAnglesZYX@g' $@
perl -pi -e's@\bfromRotationMatrix\b@FromRotationMatrix@g' $@
perl -pi -e's@\bgenerateOrthonormalBasis\b@GenerateOrthonormalBasis@g' $@
perl -pi -e's@\bgetBarycentrics\b@GetBarycentrics@g' $@
perl -pi -e's@\bgetColumn\b@GetColumn@g' $@
perl -pi -e's@\bgetColumnMajor\b@GetColumnMajor@g' $@
perl -pi -e's@\bgetRow\b@GetRow@g' $@
perl -pi -e's@\bgolubKahanStep\b@GolubKahanStep@g' $@
perl -pi -e's@\bintermediate\b@Intermediate@g' $@
perl -pi -e's@\bintervalRandom\b@IntervalRandom@g' $@
perl -pi -e's@\binvSqRoot\b@InvSqrt@g' $@
perl -pi -e's@\binverse\b@Inverse@g' $@
perl -pi -e's@\blength\b@Length@g' $@
perl -pi -e's@\blog\b@Log@g' $@
perl -pi -e's@\blogarithm\b@Log@g' $@
perl -pi -e's@\bmakeDiagonal\b@MakeDiagonal@g' $@
perl -pi -e's@\bmakeIdentity\b@MakeIdentity@g' $@
perl -pi -e's@\bmakeObliqueProjection\b@MakeObliqueProjection@g' $@
perl -pi -e's@\bmakePerspectiveProjection\b@MakePerspectiveProjection@g' $@
perl -pi -e's@\bmakeReflection\b@MakeReflection@g' $@
perl -pi -e's@\bmakeTensorProduct\b@MakeTensorProduct@g' $@
perl -pi -e's@\bmakeZero\b@MakeZero@g' $@
perl -pi -e's@\bnormalize\b@Normalize@g' $@
perl -pi -e's@\borthonormalize\b@Orthonormalize@g' $@
perl -pi -e's@\bperp\b@Perp@g' $@
perl -pi -e's@\bpower\b@Pow@g' $@
perl -pi -e's@\bqForm\b@QForm@g' $@
perl -pi -e's@\brotate\b@Rotate@g' $@
perl -pi -e's@\broundDown\b@Floor@g' $@
perl -pi -e's@\broundUp\b@Ceil@g' $@
perl -pi -e's@\bsetColumn\b@SetColumn@g' $@
perl -pi -e's@\bsetRow\b@SetRow@g' $@
perl -pi -e's@\bsign\b@Sign@g' $@
perl -pi -e's@\bsingularValueComposition\b@SingularValueComposition@g' $@
perl -pi -e's@\bsingularValueDecomposition\b@SingularValueDecomposition@g' $@
perl -pi -e's@\bsinus\b@Sin@g' $@
perl -pi -e's@\bslerp\b@Slerp@g' $@
perl -pi -e's@\bslerpExtraSpins\b@SlerpExtraSpins@g' $@
perl -pi -e's@\bsqRoot\b@Sqrt@g' $@
perl -pi -e's@\bsqr\b@Sqr@g' $@
perl -pi -e's@\bsquad\b@Squad@g' $@
perl -pi -e's@\bsquaredLength\b@SquaredLength@g' $@
perl -pi -e's@\bsymmetricRandom\b@SymmetricRandom@g' $@
perl -pi -e's@\btangent\b@Tan@g' $@
perl -pi -e's@\btimesDiagonal\b@TimesDiagonal@g' $@
perl -pi -e's@\btimesTranspose\b@TimesTranspose@g' $@
perl -pi -e's@\btoAngle\b@ToAngle@g' $@
perl -pi -e's@\btoAxisAngle\b@ToAxisAngle@g' $@
perl -pi -e's@\btoEulerAnglesXYZ\b@ToEulerAnglesXYZ@g' $@
perl -pi -e's@\btoEulerAnglesXZY\b@ToEulerAnglesXZY@g' $@
perl -pi -e's@\btoEulerAnglesYXZ\b@ToEulerAnglesYXZ@g' $@
perl -pi -e's@\btoEulerAnglesYZX\b@ToEulerAnglesYZX@g' $@
perl -pi -e's@\btoEulerAnglesZXY\b@ToEulerAnglesZXY@g' $@
perl -pi -e's@\btoEulerAnglesZYX\b@ToEulerAnglesZYX@g' $@
perl -pi -e's@\btoRotationMatrix\b@ToRotationMatrix@g' $@
perl -pi -e's@\btranspose\b@Transpose@g' $@
perl -pi -e's@\btransposeTimes\b@TransposeTimes@g' $@
perl -pi -e's@\btridiagonalize\b@Tridiagonalize@g' $@
perl -pi -e's@\bunitCross\b@UnitCross@g' $@
perl -pi -e's@\bunitPerp\b@UnitPerp@g' $@
perl -pi -e's@\bunitRandom\b@UnitRandom@g' $@
perl -pi -e's@\bw\(\)\b@W()@g' $@
perl -pi -e's@\bx\(\)\b@X()@g' $@
perl -pi -e's@\by\(\)\b@Y()@g' $@
perl -pi -e's@\bz\(\)\b@Z()@g' $@
