# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./yade/Interaction
# Target is a library:  

CONFIG += release \
          warn_on \
          staticlib 
TEMPLATE = lib 
