# File generated by kdevelop qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./RenderingEngine/GLDrawGeometricalModel
# Target is a subdirs project 

SUBDIRS += GLDrawTetrahedron \
           GLDrawBox \
           GLDrawMesh2D \
           GLDrawSphere 
CONFIG += debug \
          thread \
warn_on
TEMPLATE = subdirs
INCLUDEPATH += /usr/local/include

