# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./Engine/StandAloneEngine
# Target is a subdirs project 

SUBDIRS += ErrorTolerantLaw 
CONFIG += release \
warn_on
TEMPLATE = subdirs
