# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/Engine/Sensor/RenderingEngine/OpenGLRenderingEngine
# Target is a subdirs project 

SUBDIRS += OpenGLRenderingEngine \
           GLDrawBoundingVolume \
           GLDrawGeometricalModel \
           GLDrawInteractingGeometry \
           GLDrawShadowVolume 
CONFIG += debug \
warn_on
TEMPLATE = subdirs
