# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./Engine/EngineUnit
# Target is a subdirs project 

SUBDIRS += Box2AABB \
           InteractionDescriptionSet2AABB \
           LeapFrogOrientationIntegrator \
           LeapFrogPositionIntegrator \
           NewtonsForceLaw \
           NewtonsMomentumLaw \
           Sphere2AABB 
CONFIG += release \
warn_on
TEMPLATE = subdirs
