# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./RenderingEngine
# Target is a subdirs project 

SUBDIRS += GLDrawLineSegment 
CONFIG += debug \
warn_on
TEMPLATE = subdirs
INCLUDEPATH += /usr/local/include

