# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/Engine/EngineUnit/BodyEngineUnit/StateEngineUnit
# Target is a subdirs project 

SUBDIRS += TimeIntegrator 
CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
