# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins/InteractionPhysicsEngineUnit
# Target is a subdirs project 

SUBDIRS += ElasticContactParameters
CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
